# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlistforcast',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name=b'\xe5\x88\x86\xe5\x85\xac\xe5\x8f\xb8'),
        ),
    ]
