# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-29 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name=b'\xe5\x88\x86\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('company_code', models.CharField(max_length=6, verbose_name=b'\xe5\x88\x86\xe5\x85\xac\xe5\x8f\xb8\xe4\xbb\xa3\xe7\xa0\x81')),
            ],
            options={
                'verbose_name': '\u5206\u516c\u53f8\u8bbe\u7f6e',
                'verbose_name_plural': '\u5206\u516c\u53f8\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name=b'\xe5\x88\x86\xe5\x85\xac\xe5\x8f\xb8')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name=b'\xe5\x88\x86\xe6\xa0\xa1\xe5\x90\x8d\xe7\xa7\xb0')),
                ('school_master', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe5\x88\x86\xe6\xa0\xa1\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba')),
            ],
            options={
                'verbose_name': '\u5206\u6821\u8bbe\u7f6e',
                'verbose_name_plural': '\u5206\u6821\u8bbe\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.School', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x88\x86\xe6\xa0\xa1'),
        ),
    ]
